const SUCCESS = '_SUCCESS';
const FAILED = '_FAILED';

export const TweetActions = {
    ADD_TWEET: 'ADD_TWEET',
    ADD_TWEET_SUCCESS: 'ADD_TWEET' + SUCCESS,
    ADD_TWEET_FAILED: 'ADD_TWEET' + FAILED,
    LIKE_TWEET: 'LIKE_TWEET',
    LIKE_TWEET_SUCCESS: 'LIKE_TWEET' + SUCCESS,
    LIKE_TWEET_FAILED: 'LIKE_TWEET' + FAILED,
    SET_TWEETS: 'SET_TWEETS',
    SET_TWEETS_SUCCESS: 'SET_TWEETS' + SUCCESS,
    SET_TWEETS_FAILED: 'SET_TWEETS' + FAILED,
}

export const NotificationsActions = {
    SET_NOTIFICATIONS: 'SET_NOTIFICATIONS',
    SET_NOTIFICATIONS_SUCCESS: 'SET_NOTIFICATIONS' + SUCCESS,
    SET_NOTIFICATIONS_FAILED: 'SET_NOTIFICATIONS' + FAILED,
    ADD_NOTIFICATION: 'ADD_NOTIFICATION',
    ADD_NOTIFICATION_SUCCESS: 'ADD_NOTIFICATION' + SUCCESS,
    ADD_NOTIFICATION_FAILED: 'ADD_NOTIFICATION' + FAILED,
}

